import { NextRequest, NextResponse } from 'next/server';
import { Document, Packer, Paragraph, TextRun } from 'docx';
import { connectToDatabase, Report } from '@/lib/db';

export async function GET(req: NextRequest) {
    const jobId = req.nextUrl.searchParams.get('jobId');
    if (!jobId) return NextResponse.json({ error: 'Missing jobId' }, { status: 400 });

    try {
        await connectToDatabase();
        const report = await Report.findOne({ jobId });
        if (!report || report.status !== 'COMPLETED') {
             return NextResponse.json({ error: 'Report not ready' }, { status: 404 });
        }

        const m = report.metadataJSON || {};
        
        const doc = new Document({
            sections: [{
                properties: {},
                children: [
                    new Paragraph({
                        children: [
                            new TextRun({ text: "Generated by Flow AI - AetherLabs", bold: true, size: 36 }),
                        ],
                    }),
                    new Paragraph({
                        children: [
                            new TextRun({ text: "Policy Intelligence Report", italics: true, size: 28 }),
                        ],
                        spacing: { after: 400 }
                    }),
                    ...Object.keys(m).map(k => new Paragraph({
                        children: [
                            new TextRun({ text: `${k}: `, bold: true }),
                            new TextRun({ text: `${m[k]}` })
                        ]
                    })),
                    new Paragraph({ text: "", spacing: { after: 400 } }),
                    new Paragraph({
                        children: [
                            new TextRun({ text: `Overall Risk Score: ${report.riskScore}/100`, bold: true, color: report.riskScore > 70 ? 'FF0000' : '00AA00', size: 32 }),
                        ],
                        spacing: { after: 200 }
                    }),
                    new Paragraph({
                        children: [
                            new TextRun({ text: "Key Risk Flags & Exclusions:", bold: true, size: 28 }),
                        ],
                        spacing: { after: 200 }
                    }),
                    ...(report.flags || []).map((f: string) => new Paragraph({
                        text: `• ${f}`,
                        bullet: { level: 0 }
                    }))
                ],
            }],
        });

        const buffer = await Packer.toBuffer(doc);

        return new NextResponse(buffer as unknown as BodyInit, {
             headers: {
                 'Content-Type': 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
                 'Content-Disposition': `attachment; filename="Flow_AI_Policy_Report_${m.policyNumber || 'Export'}.docx"`
             }
        });

    } catch (error: any) {
        console.error("Word Generation Error", error);
        return NextResponse.json({ error: 'Generate failed' }, { status: 500 });
    }
}
