import { NextRequest, NextResponse } from 'next/server';
import { jsPDF } from 'jspdf';
import { connectToDatabase, Report } from '@/lib/db';

export const runtime = 'nodejs';

export async function GET(req: NextRequest) {
    const jobId = req.nextUrl.searchParams.get('jobId');
    if (!jobId) return NextResponse.json({ error: 'Missing jobId' }, { status: 400 });

    try {
        await connectToDatabase();
        const report = await Report.findOne({ jobId });
        if (!report || report.status !== 'COMPLETED') {
            return NextResponse.json({ error: 'Report not ready' }, { status: 404 });
        }

        const m = report.metadataJSON || {};
        const riskScore = report.riskScore || 0;
        const flags = report.flags || [];

        const doc = new jsPDF();

        // ── Styling & Content ──

        // Header
        doc.setFontSize(24);
        doc.setTextColor('#1d4ed8');
        doc.text('Flow AI Policy Intelligence', 105, 20, { align: 'center' });

        doc.setFontSize(12);
        doc.setTextColor('#6b7280');
        doc.text('Generated by AetherLabs', 105, 28, { align: 'center' });

        // Risk Score section
        const scoreColor = riskScore >= 70 ? '#dc2626' : riskScore >= 40 ? '#d97706' : '#059669';
        doc.setFontSize(16);
        doc.setTextColor('#111827');
        doc.text('Overall Risk Score', 20, 50);

        doc.setFontSize(28);
        doc.setTextColor(scoreColor);
        doc.text(`${riskScore} / 100`, 20, 62);

        // Policy Metadata
        doc.setFontSize(16);
        doc.setTextColor('#111827');
        doc.text('Policy Overview', 20, 85);

        let yPos = 95;
        const printRow = (key: string, value: any) => {
            if (!value || String(value) === "N/A" || String(value) === "null") return;
            doc.setFontSize(10);
            doc.setTextColor('#4b5563');
            doc.text(`${key}: `, 20, yPos);
            doc.setTextColor('#111827');
            doc.text(String(value), 60, yPos);
            yPos += 7;
        };

        printRow('Policy Holder Name', m.policyHolderName);
        printRow('Policy Number', m.policyNumber);
        printRow('Policy Type', m.policyType);
        printRow('Insurer', m.insurerName);
        printRow('Premium', m.premiumAmount);
        printRow('Sum Insured', m.sumInsured);
        printRow('Deductibles', m.deductibles);
        printRow('Start Date', m.startDate);
        printRow('Expiry Date', m.expiryDate);

        // Risk Flags
        if (flags.length > 0) {
            yPos += 10;
            doc.setFontSize(16);
            doc.setTextColor('#111827');
            doc.text('Key Exclusions & Risk Flags', 20, yPos);
            yPos += 10;

            flags.forEach((f: string) => {
                doc.setFontSize(11);
                doc.setTextColor('#dc2626');
                const lines = doc.splitTextToSize(`• ${f}`, 170);
                doc.text(lines, 20, yPos);
                yPos += (lines.length * 6) + 2;
            });
        }

        // Footer
        doc.setFontSize(9);
        doc.setTextColor('#9ca3af');
        doc.text('This is an AI generated summary. Please refer to the original policy document for legal terms.', 105, 280, { align: 'center' });

        const pdfBuffer = doc.output('arraybuffer');

        return new Response(pdfBuffer as BodyInit, {
            headers: {
                'Content-Type': 'application/pdf',
                'Content-Disposition': `attachment; filename="Flow_AI_Policy_Report_${m.policyNumber || 'Export'}.pdf"`
            }
        });

    } catch (error: unknown) {
        const err = error as Error;
        console.error("PDF Generation Error", err);
        return NextResponse.json({ error: 'Generate failed', details: err.message }, { status: 500 });
    }
}
